### ISSUE TITLE
Шумы Перлина

### ISSUE THREAD

**Issue by NikitaAstakhov2003** [coronalabs/corona-docs#69]
Как можно добавить и присвоить изображения к коду, где создан шум Перлина для того, чтобы шум Перлина был выведен присвоенными изображениями на эмулятор смартфона в движке Corona на языке lua? Если есть шаблон, прошу скинуть его или показать. Формат шума Перлина, 2D.

**Comment by Shchvova** [comment]
Sorry. This is much more [forums](https://forums.solar2d.com/) question, rather than a bug or issue with documentation. I tried searching for "Water Shader" there and got a bunch of results. Here is one, for example:  http://goo.gl/fBSbWi
This is a Fragment for the [custom effect](https://docs.coronalabs.com/guide/graphics/customEffects.html), which you can assign to textures.
If you want specifically Perlin noise for some reason, you can take Solar2D [implementation](https://github.com/coronalabs/corona/blob/master/librtt/Display/Shader/kernel_generator_perlinNoise_gl.lua) a a start and do it yourself.
